version: '3.4'

networks:
    collabtag-dev:
        driver: bridge 

services:
    collabtag-backend:
        image: collabtag-backend:latest
        depends_on:
            - "postgres"
        build:
        context: ./backend/backend
        dockerfile: Dockerfile
        ports:
            - "5000:5000"     
        environment:
            DB_CONNECTION_STRING: "host=postgres;port=5432;database=blogdb;username=bloguser;password=bloguser"
        networks:
            - collabtag-dev
    
    postgres:
        image: postgres:latest
        ports:
            - "5432"
        restart: always
        volumes:
            - db_volume:/var/lib/postgresql/data
            - ./postgres/collabtag_DLL.sql :/docker-entrypoint-initdb.d/seed.sql
        environment:
            POSTGRES_USER: "bloguser"
            POSTGRES_PASSWORD: "bloguser"
            POSTGRES_DB: "blogdb"
        networks:
            - collabtag-dev
volumes:
    db_volume: